# Base configs
baseurl: "https://themellowj.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"


# UI configs
title: "Photography by Justin McGriff"
subtitle: "Capturing the important moments"
author: "Justin McGriff"
header:
 title: "Photography"
 subtitle: "by Justin McGriff"
footer:
 name: "Hey there, my name is Justin"
 bio: "I am a developer, runner, and photographer."
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/justinframe700"
  linkedin: "https://www.linkedin.com/in/justmcgriff"
  github: "https://github.com/themellowj"
